{{- range .Values.models }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .shortName }}-service
  labels:
    app: {{ .shortName }}
spec:
  type: NodePort
  selector:
    app: {{ .shortName }}
    tier: {{ .shortName }}
  ports:
  - port: 80
    targetPort: 80
---
{{- end }}